-- Task 9-1-4 (2026-08-22): 레거시 카테고리(PARK/SPORTS/CULTURE/FESTIVAL/EXHIBITION/PERFORMANCE/
-- POPUP/RESERVATION) 표기를 완전히 제거하고 5대 UI 카테고리로 통합한다.
-- 매핑 근거: spec/data/ai-rule.md 3.3 (Decision 008 공식 매핑표, "제안됨(코드 미반영)" 상태였던
-- 것을 실제 데이터에 반영) — 🌳 야외·자연←PARK / 🏛️ 전시·박물관←CULTURE,EXHIBITION /
-- 🎪 공연·축제←FESTIVAL,PERFORMANCE / 🎡 키즈·액티비티←SPORTS,POPUP,RESERVATION.
-- 임의 추측 아님: 실측 확인 결과 EXHIBITION/FESTIVAL/PERFORMANCE/POPUP은 SEOUL_CULTURE(활성
-- 어댑터)가 만든 값이라 코드 수정 후 재수집으로도 갱신되지만, RESERVATION(2,544건)은
-- SEOUL_RESERVATION 접두사로 현재 활성 어댑터가 전혀 없는 폐기된 소스의 잔존 데이터라 이
-- 백필이 유일한 정정 경로다.

UPDATE events
SET event_type = CASE event_type
  WHEN 'FESTIVAL' THEN 'PERFORMANCE_FESTIVAL'
  WHEN 'PERFORMANCE' THEN 'PERFORMANCE_FESTIVAL'
  WHEN 'EXHIBITION' THEN 'EXHIBITION_MUSEUM'
  WHEN 'CULTURE' THEN 'EXHIBITION_MUSEUM'
  WHEN 'POPUP' THEN 'KIDS_ACTIVITY'
  WHEN 'RESERVATION' THEN 'KIDS_ACTIVITY'
  WHEN 'SPORTS' THEN 'KIDS_ACTIVITY'
  ELSE event_type
END
WHERE event_type IN ('FESTIVAL', 'PERFORMANCE', 'EXHIBITION', 'CULTURE', 'POPUP', 'RESERVATION', 'SPORTS');

UPDATE open_spaces
SET category = CASE category
  WHEN 'PARK' THEN 'OUTDOOR_NATURE'
  WHEN 'CULTURE' THEN 'EXHIBITION_MUSEUM'
  WHEN 'EXHIBITION' THEN 'EXHIBITION_MUSEUM'
  WHEN 'FESTIVAL' THEN 'PERFORMANCE_FESTIVAL'
  WHEN 'PERFORMANCE' THEN 'PERFORMANCE_FESTIVAL'
  WHEN 'POPUP' THEN 'KIDS_ACTIVITY'
  WHEN 'RESERVATION' THEN 'KIDS_ACTIVITY'
  WHEN 'SPORTS' THEN 'KIDS_ACTIVITY'
  ELSE category
END
WHERE category IN ('PARK', 'CULTURE', 'EXHIBITION', 'FESTIVAL', 'PERFORMANCE', 'POPUP', 'RESERVATION', 'SPORTS');
