-- Task 9-6-8(2026-08-23): 전국 sigungu_name에서 광역 지자체(도/특별시/광역시) 접두가
-- 빠진 값을 scripts/ingest/adapters/lib/korea-region-lookup.mjs의 정규화 표 기준으로
-- 일괄 정정한다. 변환은 결정적(같은 원본값은 항상 같은 결과)이라 시/군/구별 UPDATE 1건씩
-- 실행하며, 여러 광역에 동일 이름이 존재해 판별 불가능한 값(남구/서구/강서구/고성군/광주시
-- 등)과 원인 불명 오염값(공공주택지구/택시 등)은 정규화 표에서 제외돼 있어 이 마이그레이션도
-- 자동으로 손대지 않는다(추측 금지).

-- events: 122건 변환
UPDATE events SET sigungu_name = '경기도 가평군' WHERE sigungu_name = '가평군';
UPDATE events SET sigungu_name = '강원특별자치도 강릉시' WHERE sigungu_name = '강릉시';
UPDATE events SET sigungu_name = '경상남도 거제시' WHERE sigungu_name = '거제시';
UPDATE events SET sigungu_name = '경상남도 거창군' WHERE sigungu_name = '거창군';
UPDATE events SET sigungu_name = '경상북도 경산시' WHERE sigungu_name = '경산시';
UPDATE events SET sigungu_name = '경상북도 경주시' WHERE sigungu_name = '경주시';
UPDATE events SET sigungu_name = '충청남도 계룡시' WHERE sigungu_name = '계룡시';
UPDATE events SET sigungu_name = '경상북도 고령군' WHERE sigungu_name = '고령군';
UPDATE events SET sigungu_name = '경기도 고양시' WHERE sigungu_name = '고양시';
UPDATE events SET sigungu_name = '경기도 고양시 덕양구' WHERE sigungu_name = '고양시 덕양구';
UPDATE events SET sigungu_name = '경기도 고양시 일산동구' WHERE sigungu_name = '고양시 일산동구';
UPDATE events SET sigungu_name = '전북특별자치도 고창군' WHERE sigungu_name = '고창군';
UPDATE events SET sigungu_name = '전라남도 고흥군' WHERE sigungu_name = '고흥군';
UPDATE events SET sigungu_name = '충청남도 공주시' WHERE sigungu_name = '공주시';
UPDATE events SET sigungu_name = '경기도 과천시' WHERE sigungu_name = '과천시';
UPDATE events SET sigungu_name = '경기도 광명시' WHERE sigungu_name = '광명시';
UPDATE events SET sigungu_name = '서울특별시 광진구' WHERE sigungu_name = '광진구';
UPDATE events SET sigungu_name = '충청북도 괴산군' WHERE sigungu_name = '괴산군';
UPDATE events SET sigungu_name = '경기도 구리시' WHERE sigungu_name = '구리시';
UPDATE events SET sigungu_name = '경상북도 구미시' WHERE sigungu_name = '구미시';
UPDATE events SET sigungu_name = '전북특별자치도 군산시' WHERE sigungu_name = '군산시';
UPDATE events SET sigungu_name = '경기도 군포시' WHERE sigungu_name = '군포시';
UPDATE events SET sigungu_name = '충청남도 금산군' WHERE sigungu_name = '금산군';
UPDATE events SET sigungu_name = '부산광역시 기장군' WHERE sigungu_name = '기장군';
UPDATE events SET sigungu_name = '전북특별자치도 김제시' WHERE sigungu_name = '김제시';
UPDATE events SET sigungu_name = '경상북도 김천시' WHERE sigungu_name = '김천시';
UPDATE events SET sigungu_name = '경기도 김포시' WHERE sigungu_name = '김포시';
UPDATE events SET sigungu_name = '경상남도 김해시' WHERE sigungu_name = '김해시';
UPDATE events SET sigungu_name = '전라남도 나주시' WHERE sigungu_name = '나주시';
UPDATE events SET sigungu_name = '경기도 남양주시' WHERE sigungu_name = '남양주시';
UPDATE events SET sigungu_name = '대구광역시 달성군' WHERE sigungu_name = '달성군';
UPDATE events SET sigungu_name = '경기도 동두천시' WHERE sigungu_name = '동두천시';
UPDATE events SET sigungu_name = '전라남도 목포시' WHERE sigungu_name = '목포시';
UPDATE events SET sigungu_name = '전라남도 무안군' WHERE sigungu_name = '무안군';
UPDATE events SET sigungu_name = '전북특별자치도 무주군' WHERE sigungu_name = '무주군';
UPDATE events SET sigungu_name = '경상북도 문경시' WHERE sigungu_name = '문경시';
UPDATE events SET sigungu_name = '경상남도 밀양시' WHERE sigungu_name = '밀양시';
UPDATE events SET sigungu_name = '충청남도 보령시' WHERE sigungu_name = '보령시';
UPDATE events SET sigungu_name = '충청북도 보은군' WHERE sigungu_name = '보은군';
UPDATE events SET sigungu_name = '충청남도 부여군' WHERE sigungu_name = '부여군';
UPDATE events SET sigungu_name = '경기도 부천시' WHERE sigungu_name = '부천시';
UPDATE events SET sigungu_name = '경기도 부천시 원미구' WHERE sigungu_name = '부천시 원미구';
UPDATE events SET sigungu_name = '경상남도 사천시' WHERE sigungu_name = '사천시';
UPDATE events SET sigungu_name = '경상남도 산청군' WHERE sigungu_name = '산청군';
UPDATE events SET sigungu_name = '경상북도 상주시' WHERE sigungu_name = '상주시';
UPDATE events SET sigungu_name = '제주특별자치도 서귀포시' WHERE sigungu_name = '서귀포시';
UPDATE events SET sigungu_name = '충청남도 서산시' WHERE sigungu_name = '서산시';
UPDATE events SET sigungu_name = '충청남도 서천군' WHERE sigungu_name = '서천군';
UPDATE events SET sigungu_name = '경기도 성남시' WHERE sigungu_name = '성남시';
UPDATE events SET sigungu_name = '경기도 성남시 분당구' WHERE sigungu_name = '성남시 분당구';
UPDATE events SET sigungu_name = '경기도 수원시' WHERE sigungu_name = '수원시';
UPDATE events SET sigungu_name = '경기도 수원시 영통구' WHERE sigungu_name = '수원시 영통구';
UPDATE events SET sigungu_name = '경기도 수원시 팔달구' WHERE sigungu_name = '수원시 팔달구';
UPDATE events SET sigungu_name = '전북특별자치도 순창군' WHERE sigungu_name = '순창군';
UPDATE events SET sigungu_name = '경기도 시흥시' WHERE sigungu_name = '시흥시';
UPDATE events SET sigungu_name = '경상북도 안동시' WHERE sigungu_name = '안동시';
UPDATE events SET sigungu_name = '경기도 안산시' WHERE sigungu_name = '안산시';
UPDATE events SET sigungu_name = '경기도 안산시 단원구' WHERE sigungu_name = '안산시 단원구';
UPDATE events SET sigungu_name = '경기도 안산시 상록구' WHERE sigungu_name = '안산시 상록구';
UPDATE events SET sigungu_name = '경기도 안성시' WHERE sigungu_name = '안성시';
UPDATE events SET sigungu_name = '경기도 안양시' WHERE sigungu_name = '안양시';
UPDATE events SET sigungu_name = '경기도 안양시 동안구' WHERE sigungu_name = '안양시 동안구';
UPDATE events SET sigungu_name = '경기도 안양시 만안구' WHERE sigungu_name = '안양시 만안구';
UPDATE events SET sigungu_name = '강원특별자치도 양구군' WHERE sigungu_name = '양구군';
UPDATE events SET sigungu_name = '경기도 양주시' WHERE sigungu_name = '양주시';
UPDATE events SET sigungu_name = '경기도 양평군' WHERE sigungu_name = '양평군';
UPDATE events SET sigungu_name = '전라남도 여수시' WHERE sigungu_name = '여수시';
UPDATE events SET sigungu_name = '경기도 여주시' WHERE sigungu_name = '여주시';
UPDATE events SET sigungu_name = '경기도 연천군' WHERE sigungu_name = '연천군';
UPDATE events SET sigungu_name = '전라남도 영광군' WHERE sigungu_name = '영광군';
UPDATE events SET sigungu_name = '경상북도 영덕군' WHERE sigungu_name = '영덕군';
UPDATE events SET sigungu_name = '충청북도 영동군' WHERE sigungu_name = '영동군';
UPDATE events SET sigungu_name = '강원특별자치도 영월군' WHERE sigungu_name = '영월군';
UPDATE events SET sigungu_name = '경상북도 영주시' WHERE sigungu_name = '영주시';
UPDATE events SET sigungu_name = '충청남도 예산군' WHERE sigungu_name = '예산군';
UPDATE events SET sigungu_name = '경상북도 예천군' WHERE sigungu_name = '예천군';
UPDATE events SET sigungu_name = '경기도 오산시' WHERE sigungu_name = '오산시';
UPDATE events SET sigungu_name = '전북특별자치도 완주군' WHERE sigungu_name = '완주군';
UPDATE events SET sigungu_name = '경기도 용인시' WHERE sigungu_name = '용인시';
UPDATE events SET sigungu_name = '경기도 용인시 처인구' WHERE sigungu_name = '용인시 처인구';
UPDATE events SET sigungu_name = '울산광역시 울주군' WHERE sigungu_name = '울주군';
UPDATE events SET sigungu_name = '강원특별자치도 원주시' WHERE sigungu_name = '원주시';
UPDATE events SET sigungu_name = '충청북도 음성군' WHERE sigungu_name = '음성군';
UPDATE events SET sigungu_name = '경기도 의왕시' WHERE sigungu_name = '의왕시';
UPDATE events SET sigungu_name = '경기도 의정부시' WHERE sigungu_name = '의정부시';
UPDATE events SET sigungu_name = '경기도 이천시' WHERE sigungu_name = '이천시';
UPDATE events SET sigungu_name = '전북특별자치도 익산시' WHERE sigungu_name = '익산시';
UPDATE events SET sigungu_name = '전북특별자치도 임실군' WHERE sigungu_name = '임실군';
UPDATE events SET sigungu_name = '전북특별자치도 장수군' WHERE sigungu_name = '장수군';
UPDATE events SET sigungu_name = '전북특별자치도 전주시 완산구' WHERE sigungu_name = '전주시 완산구';
UPDATE events SET sigungu_name = '강원특별자치도 정선군' WHERE sigungu_name = '정선군';
UPDATE events SET sigungu_name = '전북특별자치도 정읍시' WHERE sigungu_name = '정읍시';
UPDATE events SET sigungu_name = '제주특별자치도 제주시' WHERE sigungu_name = '제주시';
UPDATE events SET sigungu_name = '충청북도 제천시' WHERE sigungu_name = '제천시';
UPDATE events SET sigungu_name = '충청북도 증평군' WHERE sigungu_name = '증평군';
UPDATE events SET sigungu_name = '전라남도 진도군' WHERE sigungu_name = '진도군';
UPDATE events SET sigungu_name = '전북특별자치도 진안군' WHERE sigungu_name = '진안군';
UPDATE events SET sigungu_name = '경상남도 진주시' WHERE sigungu_name = '진주시';
UPDATE events SET sigungu_name = '충청남도 천안시 서북구' WHERE sigungu_name = '천안시 서북구';
UPDATE events SET sigungu_name = '경상북도 청송군' WHERE sigungu_name = '청송군';
UPDATE events SET sigungu_name = '충청남도 청양군' WHERE sigungu_name = '청양군';
UPDATE events SET sigungu_name = '충청북도 청주시 청원구' WHERE sigungu_name = '청주시 청원구';
UPDATE events SET sigungu_name = '충청북도 청주시 흥덕구' WHERE sigungu_name = '청주시 흥덕구';
UPDATE events SET sigungu_name = '강원특별자치도 춘천시' WHERE sigungu_name = '춘천시';
UPDATE events SET sigungu_name = '경상북도 칠곡군' WHERE sigungu_name = '칠곡군';
UPDATE events SET sigungu_name = '경상남도 통영시' WHERE sigungu_name = '통영시';
UPDATE events SET sigungu_name = '경기도 파주시' WHERE sigungu_name = '파주시';
UPDATE events SET sigungu_name = '강원특별자치도 평창군' WHERE sigungu_name = '평창군';
UPDATE events SET sigungu_name = '경기도 평택시' WHERE sigungu_name = '평택시';
UPDATE events SET sigungu_name = '경기도 포천시' WHERE sigungu_name = '포천시';
UPDATE events SET sigungu_name = '경상북도 포항시 남구' WHERE sigungu_name = '포항시 남구';
UPDATE events SET sigungu_name = '경상북도 포항시 북구' WHERE sigungu_name = '포항시 북구';
UPDATE events SET sigungu_name = '경기도 하남시' WHERE sigungu_name = '하남시';
UPDATE events SET sigungu_name = '경상남도 함양군' WHERE sigungu_name = '함양군';
UPDATE events SET sigungu_name = '전라남도 함평군' WHERE sigungu_name = '함평군';
UPDATE events SET sigungu_name = '충청남도 홍성군' WHERE sigungu_name = '홍성군';
UPDATE events SET sigungu_name = '강원특별자치도 홍천군' WHERE sigungu_name = '홍천군';
UPDATE events SET sigungu_name = '경기도 화성시' WHERE sigungu_name = '화성시';
UPDATE events SET sigungu_name = '경기도 화성시 만세구' WHERE sigungu_name = '화성시 만세구';
UPDATE events SET sigungu_name = '경기도 화성시 효행구' WHERE sigungu_name = '화성시 효행구';
UPDATE events SET sigungu_name = '강원특별자치도 화천군' WHERE sigungu_name = '화천군';
UPDATE events SET sigungu_name = '강원특별자치도 횡성군' WHERE sigungu_name = '횡성군';

-- open_spaces: 249건 변환
UPDATE open_spaces SET sigungu_name = '경기도 가평군' WHERE sigungu_name = '가평군';
UPDATE open_spaces SET sigungu_name = '서울특별시 강남구' WHERE sigungu_name = '강남구';
UPDATE open_spaces SET sigungu_name = '서울특별시 강동구' WHERE sigungu_name = '강동구';
UPDATE open_spaces SET sigungu_name = '강원특별자치도 강릉시' WHERE sigungu_name = '강릉시';
UPDATE open_spaces SET sigungu_name = '서울특별시 강북구' WHERE sigungu_name = '강북구';
UPDATE open_spaces SET sigungu_name = '전라남도 강진군' WHERE sigungu_name = '강진군';
UPDATE open_spaces SET sigungu_name = '인천광역시 강화군' WHERE sigungu_name = '강화군';
UPDATE open_spaces SET sigungu_name = '경상남도 거제시' WHERE sigungu_name = '거제시';
UPDATE open_spaces SET sigungu_name = '경상남도 거창군' WHERE sigungu_name = '거창군';
UPDATE open_spaces SET sigungu_name = '인천광역시 검단구' WHERE sigungu_name = '검단구';
UPDATE open_spaces SET sigungu_name = '경상북도 경산시' WHERE sigungu_name = '경산시';
UPDATE open_spaces SET sigungu_name = '경상북도 경주시' WHERE sigungu_name = '경주시';
UPDATE open_spaces SET sigungu_name = '충청남도 계룡시' WHERE sigungu_name = '계룡시';
UPDATE open_spaces SET sigungu_name = '인천광역시 계양구' WHERE sigungu_name = '계양구';
UPDATE open_spaces SET sigungu_name = '경상북도 고령군' WHERE sigungu_name = '고령군';
UPDATE open_spaces SET sigungu_name = '경기도 고양시' WHERE sigungu_name = '고양시';
UPDATE open_spaces SET sigungu_name = '경기도 고양시 덕양구' WHERE sigungu_name = '고양시 덕양구';
UPDATE open_spaces SET sigungu_name = '경기도 고양시 일산동구' WHERE sigungu_name = '고양시 일산동구';
UPDATE open_spaces SET sigungu_name = '경기도 고양시 일산서구' WHERE sigungu_name = '고양시 일산서구';
UPDATE open_spaces SET sigungu_name = '전북특별자치도 고창군' WHERE sigungu_name = '고창군';
UPDATE open_spaces SET sigungu_name = '전라남도 고흥군' WHERE sigungu_name = '고흥군';
UPDATE open_spaces SET sigungu_name = '전라남도 곡성군' WHERE sigungu_name = '곡성군';
UPDATE open_spaces SET sigungu_name = '충청남도 공주시' WHERE sigungu_name = '공주시';
UPDATE open_spaces SET sigungu_name = '경기도 과천시' WHERE sigungu_name = '과천시';
UPDATE open_spaces SET sigungu_name = '서울특별시 관악구' WHERE sigungu_name = '관악구';
UPDATE open_spaces SET sigungu_name = '경기도 광명시' WHERE sigungu_name = '광명시';
UPDATE open_spaces SET sigungu_name = '광주광역시 광산구' WHERE sigungu_name = '광산구';
UPDATE open_spaces SET sigungu_name = '전라남도 광양시' WHERE sigungu_name = '광양시';
UPDATE open_spaces SET sigungu_name = '서울특별시 광진구' WHERE sigungu_name = '광진구';
UPDATE open_spaces SET sigungu_name = '충청북도 괴산군' WHERE sigungu_name = '괴산군';
UPDATE open_spaces SET sigungu_name = '전라남도 구례군' WHERE sigungu_name = '구례군';
UPDATE open_spaces SET sigungu_name = '서울특별시 구로구' WHERE sigungu_name = '구로구';
UPDATE open_spaces SET sigungu_name = '경기도 구리시' WHERE sigungu_name = '구리시';
UPDATE open_spaces SET sigungu_name = '경상북도 구미시' WHERE sigungu_name = '구미시';
UPDATE open_spaces SET sigungu_name = '전북특별자치도 군산시' WHERE sigungu_name = '군산시';
UPDATE open_spaces SET sigungu_name = '대구광역시 군위군' WHERE sigungu_name = '군위군';
UPDATE open_spaces SET sigungu_name = '경기도 군포시' WHERE sigungu_name = '군포시';
UPDATE open_spaces SET sigungu_name = '충청남도 금산군' WHERE sigungu_name = '금산군';
UPDATE open_spaces SET sigungu_name = '부산광역시 금정구' WHERE sigungu_name = '금정구';
UPDATE open_spaces SET sigungu_name = '서울특별시 금천구' WHERE sigungu_name = '금천구';
UPDATE open_spaces SET sigungu_name = '부산광역시 기장군' WHERE sigungu_name = '기장군';
UPDATE open_spaces SET sigungu_name = '경기도 용인시 기흥구' WHERE sigungu_name = '기흥구';
UPDATE open_spaces SET sigungu_name = '전북특별자치도 김제시' WHERE sigungu_name = '김제시';
UPDATE open_spaces SET sigungu_name = '경상북도 김천시' WHERE sigungu_name = '김천시';
UPDATE open_spaces SET sigungu_name = '경기도 김포시' WHERE sigungu_name = '김포시';
UPDATE open_spaces SET sigungu_name = '경상남도 김해시' WHERE sigungu_name = '김해시';
UPDATE open_spaces SET sigungu_name = '전라남도 나주시' WHERE sigungu_name = '나주시';
UPDATE open_spaces SET sigungu_name = '인천광역시 남동구' WHERE sigungu_name = '남동구';
UPDATE open_spaces SET sigungu_name = '경기도 남양주시' WHERE sigungu_name = '남양주시';
UPDATE open_spaces SET sigungu_name = '전북특별자치도 남원시' WHERE sigungu_name = '남원시';
UPDATE open_spaces SET sigungu_name = '경상남도 남해군' WHERE sigungu_name = '남해군';
UPDATE open_spaces SET sigungu_name = '서울특별시 노원구' WHERE sigungu_name = '노원구';
UPDATE open_spaces SET sigungu_name = '충청남도 논산시' WHERE sigungu_name = '논산시';
UPDATE open_spaces SET sigungu_name = '충청북도 단양군' WHERE sigungu_name = '단양군';
UPDATE open_spaces SET sigungu_name = '대구광역시 달서구' WHERE sigungu_name = '달서구';
UPDATE open_spaces SET sigungu_name = '대구광역시 달성군' WHERE sigungu_name = '달성군';
UPDATE open_spaces SET sigungu_name = '전라남도 담양군' WHERE sigungu_name = '담양군';
UPDATE open_spaces SET sigungu_name = '충청남도 당진군' WHERE sigungu_name = '당진군';
UPDATE open_spaces SET sigungu_name = '충청남도 당진시' WHERE sigungu_name = '당진시';
UPDATE open_spaces SET sigungu_name = '대전광역시 대덕구' WHERE sigungu_name = '대덕구';
UPDATE open_spaces SET sigungu_name = '경기도 고양시 덕양구' WHERE sigungu_name = '덕양구';
UPDATE open_spaces SET sigungu_name = '서울특별시 도봉구' WHERE sigungu_name = '도봉구';
UPDATE open_spaces SET sigungu_name = '서울특별시 동대문구' WHERE sigungu_name = '동대문구';
UPDATE open_spaces SET sigungu_name = '경기도 동두천시' WHERE sigungu_name = '동두천시';
UPDATE open_spaces SET sigungu_name = '부산광역시 동래구' WHERE sigungu_name = '동래구';
UPDATE open_spaces SET sigungu_name = '경기도 안양시 동안구' WHERE sigungu_name = '동안구';
UPDATE open_spaces SET sigungu_name = '서울특별시 동작구' WHERE sigungu_name = '동작구';
UPDATE open_spaces SET sigungu_name = '강원특별자치도 동해시' WHERE sigungu_name = '동해시';
UPDATE open_spaces SET sigungu_name = '경상남도 창원시 마산회원구' WHERE sigungu_name = '마산회원구';
UPDATE open_spaces SET sigungu_name = '서울특별시 마포구' WHERE sigungu_name = '마포구';
UPDATE open_spaces SET sigungu_name = '전라남도 목포시' WHERE sigungu_name = '목포시';
UPDATE open_spaces SET sigungu_name = '전라남도 무안군' WHERE sigungu_name = '무안군';
UPDATE open_spaces SET sigungu_name = '전북특별자치도 무주군' WHERE sigungu_name = '무주군';
UPDATE open_spaces SET sigungu_name = '경상북도 문경시' WHERE sigungu_name = '문경시';
UPDATE open_spaces SET sigungu_name = '인천광역시 미추홀구' WHERE sigungu_name = '미추홀구';
UPDATE open_spaces SET sigungu_name = '경상남도 밀양시' WHERE sigungu_name = '밀양시';
UPDATE open_spaces SET sigungu_name = '충청남도 보령시' WHERE sigungu_name = '보령시';
UPDATE open_spaces SET sigungu_name = '전라남도 보성군' WHERE sigungu_name = '보성군';
UPDATE open_spaces SET sigungu_name = '충청북도 보은군' WHERE sigungu_name = '보은군';
UPDATE open_spaces SET sigungu_name = '경상북도 봉화군' WHERE sigungu_name = '봉화군';
UPDATE open_spaces SET sigungu_name = '부산광역시 부산진구' WHERE sigungu_name = '부산진구';
UPDATE open_spaces SET sigungu_name = '전북특별자치도 부안군' WHERE sigungu_name = '부안군';
UPDATE open_spaces SET sigungu_name = '충청남도 부여군' WHERE sigungu_name = '부여군';
UPDATE open_spaces SET sigungu_name = '경기도 부천시' WHERE sigungu_name = '부천시';
UPDATE open_spaces SET sigungu_name = '경기도 부천시 소사구' WHERE sigungu_name = '부천시 소사구';
UPDATE open_spaces SET sigungu_name = '경기도 부천시 오정구' WHERE sigungu_name = '부천시 오정구';
UPDATE open_spaces SET sigungu_name = '경기도 부천시 원미구' WHERE sigungu_name = '부천시 원미구';
UPDATE open_spaces SET sigungu_name = '인천광역시 부평구' WHERE sigungu_name = '부평구';
UPDATE open_spaces SET sigungu_name = '부산광역시 사상구' WHERE sigungu_name = '사상구';
UPDATE open_spaces SET sigungu_name = '경상남도 사천시' WHERE sigungu_name = '사천시';
UPDATE open_spaces SET sigungu_name = '부산광역시 사하구' WHERE sigungu_name = '사하구';
UPDATE open_spaces SET sigungu_name = '경상남도 산청군' WHERE sigungu_name = '산청군';
UPDATE open_spaces SET sigungu_name = '강원특별자치도 삼척시' WHERE sigungu_name = '삼척시';
UPDATE open_spaces SET sigungu_name = '경상북도 상주시' WHERE sigungu_name = '상주시';
UPDATE open_spaces SET sigungu_name = '제주특별자치도 서귀포시' WHERE sigungu_name = '서귀포시';
UPDATE open_spaces SET sigungu_name = '서울특별시 서대문구' WHERE sigungu_name = '서대문구';
UPDATE open_spaces SET sigungu_name = '충청남도 서산시' WHERE sigungu_name = '서산시';
UPDATE open_spaces SET sigungu_name = '충청남도 서천군' WHERE sigungu_name = '서천군';
UPDATE open_spaces SET sigungu_name = '서울특별시 서초구' WHERE sigungu_name = '서초구';
UPDATE open_spaces SET sigungu_name = '인천광역시 서해구' WHERE sigungu_name = '서해구';
UPDATE open_spaces SET sigungu_name = '경기도 성남시 분당구' WHERE sigungu_name = '성남시 분당구';
UPDATE open_spaces SET sigungu_name = '경기도 성남시 수정구' WHERE sigungu_name = '성남시 수정구';
UPDATE open_spaces SET sigungu_name = '경기도 성남시 중원구' WHERE sigungu_name = '성남시 중원구';
UPDATE open_spaces SET sigungu_name = '서울특별시 성동구' WHERE sigungu_name = '성동구';
UPDATE open_spaces SET sigungu_name = '서울특별시 성북구' WHERE sigungu_name = '성북구';
UPDATE open_spaces SET sigungu_name = '경상북도 성주군' WHERE sigungu_name = '성주군';
UPDATE open_spaces SET sigungu_name = '강원특별자치도 속초시' WHERE sigungu_name = '속초시';
UPDATE open_spaces SET sigungu_name = '서울특별시 송파구' WHERE sigungu_name = '송파구';
UPDATE open_spaces SET sigungu_name = '대구광역시 수성구' WHERE sigungu_name = '수성구';
UPDATE open_spaces SET sigungu_name = '부산광역시 수영구' WHERE sigungu_name = '수영구';
UPDATE open_spaces SET sigungu_name = '경기도 수원시' WHERE sigungu_name = '수원시';
UPDATE open_spaces SET sigungu_name = '경기도 수원시 권선구' WHERE sigungu_name = '수원시 권선구';
UPDATE open_spaces SET sigungu_name = '경기도 수원시 영통구' WHERE sigungu_name = '수원시 영통구';
UPDATE open_spaces SET sigungu_name = '경기도 수원시 장안구' WHERE sigungu_name = '수원시 장안구';
UPDATE open_spaces SET sigungu_name = '경기도 수원시 팔달구' WHERE sigungu_name = '수원시 팔달구';
UPDATE open_spaces SET sigungu_name = '경기도 용인시 수지구' WHERE sigungu_name = '수지구';
UPDATE open_spaces SET sigungu_name = '전북특별자치도 순창군' WHERE sigungu_name = '순창군';
UPDATE open_spaces SET sigungu_name = '전라남도 순천시' WHERE sigungu_name = '순천시';
UPDATE open_spaces SET sigungu_name = '경기도 시흥시' WHERE sigungu_name = '시흥시';
UPDATE open_spaces SET sigungu_name = '전라남도 신안군' WHERE sigungu_name = '신안군';
UPDATE open_spaces SET sigungu_name = '충청남도 아산시' WHERE sigungu_name = '아산시';
UPDATE open_spaces SET sigungu_name = '경상북도 안동시' WHERE sigungu_name = '안동시';
UPDATE open_spaces SET sigungu_name = '경기도 안산시 단원구' WHERE sigungu_name = '안산시 단원구';
UPDATE open_spaces SET sigungu_name = '경기도 안산시 상록구' WHERE sigungu_name = '안산시 상록구';
UPDATE open_spaces SET sigungu_name = '경기도 안성시' WHERE sigungu_name = '안성시';
UPDATE open_spaces SET sigungu_name = '경기도 안양시 동안구' WHERE sigungu_name = '안양시 동안구';
UPDATE open_spaces SET sigungu_name = '경기도 안양시 만안구' WHERE sigungu_name = '안양시 만안구';
UPDATE open_spaces SET sigungu_name = '강원특별자치도 양구군' WHERE sigungu_name = '양구군';
UPDATE open_spaces SET sigungu_name = '경상남도 양산시' WHERE sigungu_name = '양산시';
UPDATE open_spaces SET sigungu_name = '강원특별자치도 양양군' WHERE sigungu_name = '양양군';
UPDATE open_spaces SET sigungu_name = '경기도 양주시' WHERE sigungu_name = '양주시';
UPDATE open_spaces SET sigungu_name = '서울특별시 양천구' WHERE sigungu_name = '양천구';
UPDATE open_spaces SET sigungu_name = '경기도 양평군' WHERE sigungu_name = '양평군';
UPDATE open_spaces SET sigungu_name = '전라남도 여수시' WHERE sigungu_name = '여수시';
UPDATE open_spaces SET sigungu_name = '경기도 여주시' WHERE sigungu_name = '여주시';
UPDATE open_spaces SET sigungu_name = '인천광역시 연수구' WHERE sigungu_name = '연수구';
UPDATE open_spaces SET sigungu_name = '부산광역시 연제구' WHERE sigungu_name = '연제구';
UPDATE open_spaces SET sigungu_name = '경기도 연천군' WHERE sigungu_name = '연천군';
UPDATE open_spaces SET sigungu_name = '전라남도 영광군' WHERE sigungu_name = '영광군';
UPDATE open_spaces SET sigungu_name = '경상북도 영덕군' WHERE sigungu_name = '영덕군';
UPDATE open_spaces SET sigungu_name = '부산광역시 영도구' WHERE sigungu_name = '영도구';
UPDATE open_spaces SET sigungu_name = '충청북도 영동군' WHERE sigungu_name = '영동군';
UPDATE open_spaces SET sigungu_name = '서울특별시 영등포구' WHERE sigungu_name = '영등포구';
UPDATE open_spaces SET sigungu_name = '전라남도 영암군' WHERE sigungu_name = '영암군';
UPDATE open_spaces SET sigungu_name = '경상북도 영양군' WHERE sigungu_name = '영양군';
UPDATE open_spaces SET sigungu_name = '강원특별자치도 영월군' WHERE sigungu_name = '영월군';
UPDATE open_spaces SET sigungu_name = '인천광역시 영종구' WHERE sigungu_name = '영종구';
UPDATE open_spaces SET sigungu_name = '경상북도 영주시' WHERE sigungu_name = '영주시';
UPDATE open_spaces SET sigungu_name = '경상북도 영천시' WHERE sigungu_name = '영천시';
UPDATE open_spaces SET sigungu_name = '경기도 수원시 영통구' WHERE sigungu_name = '영통구';
UPDATE open_spaces SET sigungu_name = '충청남도 예산군' WHERE sigungu_name = '예산군';
UPDATE open_spaces SET sigungu_name = '경상북도 예천군' WHERE sigungu_name = '예천군';
UPDATE open_spaces SET sigungu_name = '경기도 오산시' WHERE sigungu_name = '오산시';
UPDATE open_spaces SET sigungu_name = '경기도 부천시 오정구' WHERE sigungu_name = '오정구';
UPDATE open_spaces SET sigungu_name = '충청북도 옥천군' WHERE sigungu_name = '옥천군';
UPDATE open_spaces SET sigungu_name = '인천광역시 옹진군' WHERE sigungu_name = '옹진군';
UPDATE open_spaces SET sigungu_name = '전라남도 완도군' WHERE sigungu_name = '완도군';
UPDATE open_spaces SET sigungu_name = '전북특별자치도 전주시 완산구' WHERE sigungu_name = '완산구';
UPDATE open_spaces SET sigungu_name = '전북특별자치도 완주군' WHERE sigungu_name = '완주군';
UPDATE open_spaces SET sigungu_name = '서울특별시 용산구' WHERE sigungu_name = '용산구';
UPDATE open_spaces SET sigungu_name = '경기도 용인시 기흥구' WHERE sigungu_name = '용인시 기흥구';
UPDATE open_spaces SET sigungu_name = '경기도 용인시 수지구' WHERE sigungu_name = '용인시 수지구';
UPDATE open_spaces SET sigungu_name = '경기도 용인시 처인구' WHERE sigungu_name = '용인시 처인구';
UPDATE open_spaces SET sigungu_name = '경상북도 울릉군' WHERE sigungu_name = '울릉군';
UPDATE open_spaces SET sigungu_name = '울산광역시 울주군' WHERE sigungu_name = '울주군';
UPDATE open_spaces SET sigungu_name = '경상북도 울진군' WHERE sigungu_name = '울진군';
UPDATE open_spaces SET sigungu_name = '강원특별자치도 원주시' WHERE sigungu_name = '원주시';
UPDATE open_spaces SET sigungu_name = '대전광역시 유성구' WHERE sigungu_name = '유성구';
UPDATE open_spaces SET sigungu_name = '서울특별시 은평구' WHERE sigungu_name = '은평구';
UPDATE open_spaces SET sigungu_name = '충청북도 음성군' WHERE sigungu_name = '음성군';
UPDATE open_spaces SET sigungu_name = '경상남도 의령군' WHERE sigungu_name = '의령군';
UPDATE open_spaces SET sigungu_name = '경상북도 의성군' WHERE sigungu_name = '의성군';
UPDATE open_spaces SET sigungu_name = '경기도 의왕시' WHERE sigungu_name = '의왕시';
UPDATE open_spaces SET sigungu_name = '경기도 의정부시' WHERE sigungu_name = '의정부시';
UPDATE open_spaces SET sigungu_name = '경상남도 창원시 의창구' WHERE sigungu_name = '의창구';
UPDATE open_spaces SET sigungu_name = '경기도 이천시' WHERE sigungu_name = '이천시';
UPDATE open_spaces SET sigungu_name = '전북특별자치도 익산시' WHERE sigungu_name = '익산시';
UPDATE open_spaces SET sigungu_name = '강원특별자치도 인제군' WHERE sigungu_name = '인제군';
UPDATE open_spaces SET sigungu_name = '경기도 고양시 일산동구' WHERE sigungu_name = '일산동구';
UPDATE open_spaces SET sigungu_name = '전북특별자치도 임실군' WHERE sigungu_name = '임실군';
UPDATE open_spaces SET sigungu_name = '전라남도 장성군' WHERE sigungu_name = '장성군';
UPDATE open_spaces SET sigungu_name = '전북특별자치도 장수군' WHERE sigungu_name = '장수군';
UPDATE open_spaces SET sigungu_name = '전라남도 장흥군' WHERE sigungu_name = '장흥군';
UPDATE open_spaces SET sigungu_name = '전북특별자치도 전주시 덕진구' WHERE sigungu_name = '전주시 덕진구';
UPDATE open_spaces SET sigungu_name = '전북특별자치도 전주시 완산구' WHERE sigungu_name = '전주시 완산구';
UPDATE open_spaces SET sigungu_name = '강원특별자치도 정선군' WHERE sigungu_name = '정선군';
UPDATE open_spaces SET sigungu_name = '전북특별자치도 정읍시' WHERE sigungu_name = '정읍시';
UPDATE open_spaces SET sigungu_name = '인천광역시 제물포구' WHERE sigungu_name = '제물포구';
UPDATE open_spaces SET sigungu_name = '제주특별자치도 제주시' WHERE sigungu_name = '제주시';
UPDATE open_spaces SET sigungu_name = '충청북도 제천시' WHERE sigungu_name = '제천시';
UPDATE open_spaces SET sigungu_name = '서울특별시 종로구' WHERE sigungu_name = '종로구';
UPDATE open_spaces SET sigungu_name = '서울특별시 중랑구' WHERE sigungu_name = '중랑구';
UPDATE open_spaces SET sigungu_name = '충청북도 증평군' WHERE sigungu_name = '증평군';
UPDATE open_spaces SET sigungu_name = '전라남도 진도군' WHERE sigungu_name = '진도군';
UPDATE open_spaces SET sigungu_name = '전북특별자치도 진안군' WHERE sigungu_name = '진안군';
UPDATE open_spaces SET sigungu_name = '경상남도 진주시' WHERE sigungu_name = '진주시';
UPDATE open_spaces SET sigungu_name = '충청북도 진천군' WHERE sigungu_name = '진천군';
UPDATE open_spaces SET sigungu_name = '경상남도 창녕군' WHERE sigungu_name = '창녕군';
UPDATE open_spaces SET sigungu_name = '경상남도 창원시' WHERE sigungu_name = '창원시';
UPDATE open_spaces SET sigungu_name = '경상남도 창원시 마산합포구' WHERE sigungu_name = '창원시 마산합포구';
UPDATE open_spaces SET sigungu_name = '경상남도 창원시 마산회원구' WHERE sigungu_name = '창원시 마산회원구';
UPDATE open_spaces SET sigungu_name = '경상남도 창원시 성산구' WHERE sigungu_name = '창원시 성산구';
UPDATE open_spaces SET sigungu_name = '경상남도 창원시 의창구' WHERE sigungu_name = '창원시 의창구';
UPDATE open_spaces SET sigungu_name = '경상남도 창원시 진해구' WHERE sigungu_name = '창원시 진해구';
UPDATE open_spaces SET sigungu_name = '경기도 용인시 처인구' WHERE sigungu_name = '처인구';
UPDATE open_spaces SET sigungu_name = '충청남도 천안시' WHERE sigungu_name = '천안시';
UPDATE open_spaces SET sigungu_name = '충청남도 천안시 동남구' WHERE sigungu_name = '천안시 동남구';
UPDATE open_spaces SET sigungu_name = '충청남도 천안시 서북구' WHERE sigungu_name = '천안시 서북구';
UPDATE open_spaces SET sigungu_name = '강원특별자치도 철원군' WHERE sigungu_name = '철원군';
UPDATE open_spaces SET sigungu_name = '경상북도 청도군' WHERE sigungu_name = '청도군';
UPDATE open_spaces SET sigungu_name = '경상북도 청송군' WHERE sigungu_name = '청송군';
UPDATE open_spaces SET sigungu_name = '충청남도 청양군' WHERE sigungu_name = '청양군';
UPDATE open_spaces SET sigungu_name = '충청북도 청주시 청원구' WHERE sigungu_name = '청원구';
UPDATE open_spaces SET sigungu_name = '충청북도 청원군' WHERE sigungu_name = '청원군';
UPDATE open_spaces SET sigungu_name = '충청북도 청주시' WHERE sigungu_name = '청주시';
UPDATE open_spaces SET sigungu_name = '충청북도 청주시 상당구' WHERE sigungu_name = '청주시 상당구';
UPDATE open_spaces SET sigungu_name = '충청북도 청주시 서원구' WHERE sigungu_name = '청주시 서원구';
UPDATE open_spaces SET sigungu_name = '충청북도 청주시 청원구' WHERE sigungu_name = '청주시 청원구';
UPDATE open_spaces SET sigungu_name = '충청북도 청주시 흥덕구' WHERE sigungu_name = '청주시 흥덕구';
UPDATE open_spaces SET sigungu_name = '강원특별자치도 춘천시' WHERE sigungu_name = '춘천시';
UPDATE open_spaces SET sigungu_name = '충청북도 충주시' WHERE sigungu_name = '충주시';
UPDATE open_spaces SET sigungu_name = '경상북도 칠곡군' WHERE sigungu_name = '칠곡군';
UPDATE open_spaces SET sigungu_name = '강원특별자치도 태백시' WHERE sigungu_name = '태백시';
UPDATE open_spaces SET sigungu_name = '충청남도 태안군' WHERE sigungu_name = '태안군';
UPDATE open_spaces SET sigungu_name = '경상남도 통영시' WHERE sigungu_name = '통영시';
UPDATE open_spaces SET sigungu_name = '경기도 파주시' WHERE sigungu_name = '파주시';
UPDATE open_spaces SET sigungu_name = '강원특별자치도 평창군' WHERE sigungu_name = '평창군';
UPDATE open_spaces SET sigungu_name = '경기도 평택시' WHERE sigungu_name = '평택시';
UPDATE open_spaces SET sigungu_name = '경기도 포천시' WHERE sigungu_name = '포천시';
UPDATE open_spaces SET sigungu_name = '경상북도 포항시 남구' WHERE sigungu_name = '포항시 남구';
UPDATE open_spaces SET sigungu_name = '경상북도 포항시 북구' WHERE sigungu_name = '포항시 북구';
UPDATE open_spaces SET sigungu_name = '경기도 하남시' WHERE sigungu_name = '하남시';
UPDATE open_spaces SET sigungu_name = '경상남도 하동군' WHERE sigungu_name = '하동군';
UPDATE open_spaces SET sigungu_name = '경상남도 함안군' WHERE sigungu_name = '함안군';
UPDATE open_spaces SET sigungu_name = '경상남도 함양군' WHERE sigungu_name = '함양군';
UPDATE open_spaces SET sigungu_name = '전라남도 함평군' WHERE sigungu_name = '함평군';
UPDATE open_spaces SET sigungu_name = '경상남도 합천군' WHERE sigungu_name = '합천군';
UPDATE open_spaces SET sigungu_name = '전라남도 해남군' WHERE sigungu_name = '해남군';
UPDATE open_spaces SET sigungu_name = '부산광역시 해운대구' WHERE sigungu_name = '해운대구';
UPDATE open_spaces SET sigungu_name = '충청남도 홍성군' WHERE sigungu_name = '홍성군';
UPDATE open_spaces SET sigungu_name = '강원특별자치도 홍천군' WHERE sigungu_name = '홍천군';
UPDATE open_spaces SET sigungu_name = '경기도 화성시' WHERE sigungu_name = '화성시';
UPDATE open_spaces SET sigungu_name = '경기도 화성시 동탄구' WHERE sigungu_name = '화성시 동탄구';
UPDATE open_spaces SET sigungu_name = '경기도 화성시 만세구' WHERE sigungu_name = '화성시 만세구';
UPDATE open_spaces SET sigungu_name = '경기도 화성시 병점구' WHERE sigungu_name = '화성시 병점구';
UPDATE open_spaces SET sigungu_name = '경기도 화성시 효행구' WHERE sigungu_name = '화성시 효행구';
UPDATE open_spaces SET sigungu_name = '전라남도 화순군' WHERE sigungu_name = '화순군';
UPDATE open_spaces SET sigungu_name = '강원특별자치도 화천군' WHERE sigungu_name = '화천군';
UPDATE open_spaces SET sigungu_name = '강원특별자치도 횡성군' WHERE sigungu_name = '횡성군';
